### ISSUE TITLE
Delay for creating/deleting rows when using firebase

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#226]
If I type "o" to enter insert mode on a new row, the UI immediately enters insert mode, but there is a random delay before it actually creates the new row and move the cursor to it (I assume waiting on a round trip to firebase?). Most of the time this isn't an issue, but rarely there will be a ~1 second delay, which is pretty disorienting. (The application always ends up in the appropriate state, it's just the UI that doesn't do well.)

I think there is a similar delay on operations that delete rows. It seems like the length of the delay is proportional to the number of rows deleted/created. For 20 rows the delay seems to consistently >= 2 seconds. Similarly for pasting many rows.

I don't know if there is an easy way to avoid this. I've never noticed a delay on operations that modify a single row though, so hopefully?

**Comment by WuTheFWasThat** [comment]
yeah, some things are noticeably slower than they used to be/compared with localstorage.  It is annoying to me, and I'd already made some efforts so that almost nothing blocks on reads from firebase except for displaying previously unloaded parts of the document

delete/clone-pasting shouldn't be proportional to the number of rows deleted/created.  I tried briefly myself and it didn't seem to be.  

In general, it's possible delays appear when there are too many writes to firebase queued up -  I don't do anything to optimize there, at the moment.  Anyways, overall these issues definitely still exist and I'll look into it a bit more

**Comment by paulfchristiano** [comment]
Yeah, it doesn't seem linear actually, it's just a consistent ~2 second delay for me.

**Comment by WuTheFWasThat** [comment]
it's less than 500ms for me though and I verified it doesn't do any gets from firebase.  you were on the most recent commit?

**Comment by paulfchristiano** [comment]
On commit 56801015a38.

If I turn off the internet and type "o" the UI hangs, in insert mode at the beginning of the line. When I reconnect to the internet it creates the new row and moves the cursor to it. So it seems like it's definitely waiting on something?

It takes < 500ms for a single row. When I cut or paste a large number of rows it definitely takes much more than that (though it's not linear).

**Comment by WuTheFWasThat** [comment]
I think the culprit was time-tracking.  Try out the branch time-tracking-fixes and see if you still observe the slowness.  (NOTE: it's not entirely backwards compatible, you'll lose the time data for deleted rows.  if the new behavior seems better I'll give you a script to backfill before it goes on master).  Actually, there was some bad behavior in time-tracking that could maybe explain why you saw linear looking delay, also.  I think I fixed the NaN issue also.  

I'm guessing the dependence on internet was also time-tracking, but don't have time to test it at the moment.  but you could try the same test with the time-tracking plugin turned off if you want

(I'm traveling the next 2 weeks so not sure when I'll have internet)

**Comment by paulfchristiano** [comment]
I get a bunch of compilation errors when I do "npm run build" on commit c7ccc0a2c76 (and the same things as javascript errors if I do "npm start"):

ERROR in ./src/assets/js/types.ts
[31, 34]: expected an assignment or function call
[43, 15]: expected an assignment or function call
[43, 37]: expected an assignment or function call
[43, 33]: Missing semicolon
[43, 43]: Missing semicolon
[43, 14]: expected property-declaration to have a typedef


ERROR in ./src/assets/js/types.ts
Module build failed: Error: Compilation failed due to tslint errors.
    at report (/Users/paulfchristiano/GoogleDrive/Projects/vimflowy/node_modules/tslint-loader/index.js:60:11)
    at Object.lint (/Users/paulfchristiano/GoogleDrive/Projects/vimflowy/node_modules/tslint-loader/index.js:44:3)
    at Object.module.exports (/Users/paulfchristiano/GoogleDrive/Projects/vimflowy/node_modules/tslint-loader/index.js:103:8)
 @ ./src/assets/js/datastore.ts 52:13-31

ERROR in [default] /Users/paulfchristiano/GoogleDrive/Projects/vimflowy/src/assets/js/types.ts:31:27 
Cannot find name 'keyof'.

ERROR in [default] /Users/paulfchristiano/GoogleDrive/Projects/vimflowy/src/assets/js/types.ts:31:33 
';' expected.

ERROR in [default] /Users/paulfchristiano/GoogleDrive/Projects/vimflowy/src/assets/js/types.ts:31:33 
Cannot find name 'CharTextProperties'.

ERROR in [default] /Users/paulfchristiano/GoogleDrive/Projects/vimflowy/src/assets/js/types.ts:43:2 
A computed property name must be of type 'string', 'number', 'symbol', or 'any'.

ERROR in [default] /Users/paulfchristiano/GoogleDrive/Projects/vimflowy/src/assets/js/types.ts:43:3 
Cannot find name 'P'.

ERROR in [default] /Users/paulfchristiano/GoogleDrive/Projects/vimflowy/src/assets/js/types.ts:43:8 
Cannot find name 'keyof'.

ERROR in [default] /Users/paulfchristiano/GoogleDrive/Projects/vimflowy/src/assets/js/types.ts:43:14 
']' expected.

ERROR in [default] /Users/paulfchristiano/GoogleDrive/Projects/vimflowy/src/assets/js/types.ts:43:14 
Cannot find name 'CharTextProperties'.

ERROR in [default] /Users/paulfchristiano/GoogleDrive/Projects/vimflowy/src/assets/js/types.ts:43:32 
';' expected.

ERROR in [default] /Users/paulfchristiano/GoogleDrive/Projects/vimflowy/src/assets/js/types.ts:43:33 
Declaration or statement expected.

ERROR in [default] /Users/paulfchristiano/GoogleDrive/Projects/vimflowy/src/assets/js/types.ts:43:34 
Declaration or statement expected.

ERROR in [default] /Users/paulfchristiano/GoogleDrive/Projects/vimflowy/src/assets/js/types.ts:43:36 
Cannot find name 'string'.

ERROR in [default] /Users/paulfchristiano/GoogleDrive/Projects/vimflowy/src/assets/js/types.ts:44:0 
Declaration or statement expected

**Comment by WuTheFWasThat** [comment]
sorry, you need to do something like `npm update typescript`.  I switched to using 2.1 from 2.0 and there are some new syntaxes

**Comment by paulfchristiano** [comment]
Waiting on the internet was time tracking. The new commit doesn't fix that problem (I'm not sure how much better it makes the delay in general---I'm currently in an area with flaky internet, so often observe significant delays).

Even moving the cursor from line to line seems to sometimes wait on the internet. (It seems I can move the cursor a few times, and then it stops working until it connects to the internet.)

**Comment by WuTheFWasThat** [comment]
There are definitely some reasons for delay, still.  It won't pass the no internet test yet.

**Comment by WuTheFWasThat** [comment]
fixed now, i think
